apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasker-ingress
  labels:
    app: tasker
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.frontend.name }}
                port:
                  number: {{ .Values.global.frontend.port }}
