apiVersion: v1
kind: Secret
metadata:
  name: tasker-backend-secret
  labels:
    app: tasker-backend
type: Opaque
stringData:
  DATABASE_URL: "postgresql://docker:docker@tasker-db:5432/tasker?schema=public"
  SECRET_JWT: supersecretjwt
