apiVersion: v1
kind: Service
metadata:
  name: tasker-backend
  labels:
    app: tasker-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
  selector:
    app: tasker-backend
