apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.name }}-secret
  labels:
    app: {{ .Values.global.db.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.db.password | quote }}
  POSTGRES_DB: {{ .Values.global.db.database | quote }}
