apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasker-db-pv
  labels:
    type: local
    app: tasker-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/tasker-db"
    type: DirectoryOrCreate
