apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasker-db-pvc
  labels:
    app: tasker-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
