apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.backend.name }}
  labels:
    app: {{ .Values.global.backend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.backend.name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - "until nc -z {{ .Values.global.db.name }} {{ .Values.global.db.port }}; do echo 'aguardando o banco...'; sleep 2; done"
      containers:
        - name: {{ .Values.global.backend.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.global.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.backend.name }}-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.backend.name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.backend.name }}-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.global.db.name }}:{{ .Values.global.db.port }}/{{ .Values.global.db.database }}?schema=public"
            - name: SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.backend.name }}-secret
                  key: SECRET_JWT
          readinessProbe:
            tcpSocket:
              port: {{ .Values.global.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
