apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.backend.name }}-secret
  labels:
    app: {{ .Values.global.backend.name }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.global.db.user }}:{{ .Values.global.db.password }}@{{ .Values.global.db.name }}:{{ .Values.global.db.port }}/{{ .Values.global.db.database }}?schema=public"
  SECRET_JWT: {{ .Values.global.backend.jwtSecret | quote }}
