apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.frontend.name }}-config
  labels:
    app: {{ .Values.global.frontend.name }}
data:
  BACKEND_URL: "http://{{ .Values.global.backend.name }}:{{ .Values.global.backend.port }}"
